#!/bin/bash

composer install
mysql -e 'drop database dkan_travis; create database dkan_travis;'

# Install DKAN
git clone --branch 7.x-1.x http://git.drupal.org/project/dkan.git
cd dkan
drush make --prepare-install build-dkan.make --yes
drush si dkan --sites-subdir=default --db-url=mysql://root:@127.0.0.1/dkan_travis --account-name=admin --account-pass=admin  --site-name="DKAN" install_configure_form.update_status_module='array(FALSE,FALSE)' --yes
drush cc all --yes

drush --root=$PWD runserver 8888 &
sleep 4
cd ../

npm install
wget http://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar
java -jar selenium-server-standalone-2.39.0.jar -p 4444 &
sleep 5

bin/behat
